spring.application.name=userservice
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:userservice}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=bhushan
spring.datasource.password=root
spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
server.port=9810

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=userinfo-consumer-group
spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer= com.user.userservice.deserializer.UserInfoDeserializer
spring.kafka.topic-json.name=user_service
spring.kafka.consumer.properties.spring.json.type.mapping=auth:com.user.userservice.entities.UserInfoDto

logging.level.org.springframework.security=DEBUG
logging.level.your.package.name=DEBUG

logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO